"""Added username

Revision ID: 58527ae3aa66
Revises: a8fb5085ab4c
Create Date: 2022-01-25 12:16:14.052984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58527ae3aa66'
down_revision = 'a8fb5085ab4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
